courses_sites:
  platzi:
    url: https://platzi.com/
    paths: ['ai/']
    reviews_suburl: 'opiniones/1/'
    queries:
      path_courses_links_list: 'div.route div.route-item a'
      course_link_anchor: 'div.Hero-info div.CourseReviews > a'
      pagination_links_list: 'div.Reviews-pagination > div > div > a'
      pagination_max_index: -2
      reviews_page_course_name: 'body > section > div.Reviews-body > div > div.col-xs-12 > div > div > a'
      reviews_list: 'div.Review'
      review_image: 'div.Review-head > figure > img'
      review_user: 'div.Review-head > div.Review-info > div.Review-name > strong'
      review_stars_list: 'div.Review-head > div.Review-info > div.Review-stars > i.icon-star.fulled'
      review_description: 'div.Review-description'
